backend/account/urls.py
from django.urls import path, re_path
from account import views as account_views
from telegram_filter import views
from django.contrib.auth import views as auth_views


app_name='account'

urlpatterns = [
    path('profile/', account_views.profile, name='profile'),
    path('profile_edit/', account_views.profile_edit, name='profile_edit'),
    path('by/<slug:username>/', account_views.account, name='account'),
    path('login/', account_views.user_login ,name='login'),
    path('account/user_logout/', account_views.user_logout, name='logout'),
    path('registration/', account_views.registration, name='registration'),
    path('resend_activation_email/', account_views.resend_activation_email, name='resend_activation_email'),
    path('activate/<uidb64>/<token>', account_views.VerificationView.as_view(), name = 'activate'),
    path('set_new_pswrd/<uidb64>/<token>', account_views.SetNewPswrdView.as_view(), name = 'set_new_pswrd'),
    path('reset_email/', account_views.RequestResetEmailView.as_view(), name = 'reset_email'),
    path('unsubscribe/<uidb64>/<token>', account_views.UnsubscribeView.as_view(), name = 'unsubscribe'),

    path('fav/<str:pk>/', account_views.favourite_add, name='favourite_add'),
    path('profile/favourites/', account_views.favourite_list, name='favourite_list'),
]

backend/board/urls.py
from django.shortcuts import render
from django.urls import include, path, re_path
from board import views, api
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework import routers

app_name='board'

# api
router = routers.DefaultRouter()
router.register(r'posts', api.BoardViewSet)
urlpatterns_api = [
    path('main_page_ads/', api.main_page_ads, name='main_page_ads'),
    path('ua_cities/', api.ua_cities, name='ua_cities'),
]
urlpatterns_api += router.urls


urlpatterns_others = [
    path('llm_chat/', views.llm_chat , name='llm_chat'),
    path('llm_generate_job_desc/', views.llm_generate_job_desc, name='llm_generate_job_desc'),

    path('how_24h_works/', views.how_24h_works, name='how_24h_works'),
    path('about_cookies/', views.about_cookies, name='about_cookies'),
    path('others_page/', views.others_page, name='others_page'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('rules/', views.website_rules, name='website_rules'),
    path('lawbook/', views.lawbook, name='lawbook'),
    path('about_us/', views.about_us, name='about_us'),
    path('for_employers/', views.for_employers, name='for_employers'),
    
    path('error_to_admin/', views.error_to_admin, name='error_to_admin'),

    path('blog/<str:slug>/', views.tw_blog_post, name='tw_blog_post'),
    path('blog/', views.tw_blog, name='tw_blog'),
    path('add_blog_post/', views.add_blog_post, name='add_blog_post'),
]

urlpatterns = [
    path('add/', views.add_save , name='add'), 
    path('add/load_image/', views.add_load_image , name='add_load_image'), 
    path('add/get_user_data/', views.add_get_user_data , name='add_get_user_data'), 
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/archive/', views.archive, name='archive'),
    path('', views.index, name='index'),
    path('ad/<str:slug>/', views.advertisement, name='advertisement'),
    path('load_more/',views.load_more,name='load_more'),
    path('get_ntu_students/', views.get_ntu_students, name='get_ntu_students'),
    path('students/<str:university>/', views.get_students, name='get_students'),
    
    path('api/v1/', include(urlpatterns_api)),

]
urlpatterns.extend(urlpatterns_others)
# urlpatterns.extend(urlpatterns_api)

backend/chat/urls.py
from django.urls import path
from . import views
app_name='chat'

urlpatterns = [
    path('', views.show_chats, name = 'show_chats'),
    path('get_last_msg/', views.get_last_msg, name = 'get_last_msg'),
    path('search_chats/', views.search_chats, name = 'search_chats'),

    path('workers_list/', views.workers_list, name='workers_list'),
    path('workers_list_a/<str:slug>/', views.workers_list_a, name='workers_list_a'),

    path('add_worker/', views.add_worker, name='add_worker'),
    path('<str:room>/', views.room, name='room'),
    path('checkview/', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

backend/telegram_filter/urls.py
from django.urls import path, include
from . import views

app_name='telegram_filter'

urlpatterns = [
    # path('telegram/', views.telegram, name='telegram'),
    path('telegram_bot/', views.get_unique_code, name='get_unique_code'),
]

backend/website/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from account.views import user_logout
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from website import settings
from .sitemaps import * # Sitemap
from django.contrib.sitemaps.views import sitemap, index
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name='website'

urlpatterns = [
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'rubric': RubricSitemap,
    'age': AgeSitemap,
    'blog':BlogSitemap,
}


urlpatterns += i18n_patterns (
    # path('admin/', admin.site.urls),
    
    path('chat/', include('chat.urls')),
    path('',include('account.urls', namespace='account')),
    path('', include('telegram_filter.urls', namespace='telegram_filter')),

    path('', include('board.urls', namespace='board')),

    # path('sitemap.xml', sitemap, {'sitemaps':sitemaps}),
    
    path('sitemap.xml', index, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.index'),
    path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path('ckeditor',include('ckeditor_uploader.urls')),

    prefix_default_language=False # чтобы не было /ru/ в строке
)

if 'rosetta' in settings.INSTALLED_APPS: # это графический редактор переведённого текста
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

admin.site.index_title = "TeenWork"
admin.site.site_header = "TeenWork Admin"
admin.site.site_title = "Admin"


# errors handlers
handler400 = 'board.views.handler400_error' # неверный запрос
handler403 = 'board.views.handler403_error' # запрещён доступ к странице
handler404 = 'board.views.handler404_error' # неверная страница
handler500 = 'board.views.handler500_error' # проблема с сервером

backend/board/views.py
from django.shortcuts import redirect, render
from .models import Board, TeenworkBlog
from .forms import BoardForm, TeenworkBlogForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .services import *
from django.templatetags.static import static
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.contrib.admin.views import decorators
import functools
from googletrans import Translator
from utils.utils import ask_llm, translate_sentence
from django.forms.models import model_to_dict


def staff_member_required(view_func):  # переопределим декоратор
    def _checklogin(request, *args, **kwargs):
        if request.user.is_active and request.user.is_staff:
            return view_func(request, *args, **kwargs)
        else:
            return redirect('board:index')
    return functools.wraps(view_func)(_checklogin)

decorators.staff_member_required = staff_member_required 



def index(request):
    return show_index(request)
@csrf_exempt
def load_more(request):
    return load_more_index_adts(request)

def advertisement(request,slug):
    return show_advertisement(request,slug)


@csrf_exempt
def llm_chat(request):
    messages_list = json.loads(request.body.decode('utf-8'))

    messages_list_str = "\n\n".join([
        f"{msg['type']}:\n{msg['value']}"
        for msg in messages_list
    ])

    prompt = f'''
You are the manager of the Ukrainian platform for teenagers "Teenwork". 
Your task is to respond to users' requests within the scope of your duties as a manager.
Attached below is a chain of messages between the manager (assistant) and the user. 
Based on this chain, give a relevant answer.
Message chain:
-----------------------------
{messages_list_str}
-----------------------------
    '''.strip()
    prompt_en = translate_sentence(prompt)
    res = ask_llm(prompt_en, 'uk')
    res = res.replace('менеджер:', '').strip()

    return JsonResponse({
        'message': res
    })



@csrf_exempt
def llm_generate_job_desc(request):
    title = json.loads(request.body.decode('utf-8'))['title']
    prompt = f'''
    You are the manager of the Ukrainian platform for work for teenagers. 
    Your task is to generate a job description for the user based on the job title
    Generate a job description with 3000 chars.
    Title: {title}
    '''.strip()
    prompt_en = translate_sentence(prompt)
    res = ask_llm(prompt_en, 'uk')
    res = res.replace('менеджер:', '').strip()

    return JsonResponse({
        'description': res
    })


@csrf_exempt 
def add_save(request):
    if request.method =='POST':
        form = BoardForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            add_advert(request, form)
            if request.user.is_authenticated:
                return redirect('account:profile')
            return redirect('board:index')
        else:
            print(form.errors)
            if request.user.is_authenticated:
                context = {
                    'form':form,
                    'not_registered':False,
                }    
            else:
                context = {
                    'form':form,
                    'not_registered':True,
                }    
            return render(request, 'board/add.html', context)
    else:
        form = BoardForm()
        if request.user.is_authenticated:
            context={
                'form':form,
                'not_registered':False,
            }       
        else:
            context={
                'form':form,
                'not_registered':True,
            }        
        return render(request, 'board/add.html', context) 

def add_get_user_data(request):
    return get_user_data(request)
    

@login_required(login_url='/login/')
def edit(request, pk):
    return edit_adt(request, pk)
 
@login_required(login_url='/login/')
def delete(request,pk):
    if request.user == Board.objects.get(pk=pk).author:
        Board.objects.get(pk=pk).delete()
        return redirect('/profile/')
    else:
        return redirect('/profile/')

@login_required(login_url='/login/')
def archive(request, pk):
    return archive_adt(request, pk)

@login_required(login_url='/login/')
def get_ntu_students(request):
    # also we can search students, who are registered in out service
    # data = Account.objects.filter(im_working_student=True, email__contains="@nmu.one")
    
    data = [
        {
            'image': static('img/students/dmytro.jfif'),
            'name': 'Дмитро',
            'surname': 'Буслов',
            'patronymic': 'Юрійович',
            'speciality': '121-19-1',
            'faculty': 'ФІТ',
            'email': 'buslov.d.y@nmu.one',
            'city': 'Дніпро',
            'birthDate': '01.01.2001',
        },
        {
            'image': static('img/students/kristina.jfif'),
            'name': 'Кристина',
            'surname': 'Андрющенко',
            'patronymic': 'Сергіївна',
            'speciality': '121-19-1',
            'faculty': 'ФІТ',
            'email': 'andriushchenko.k.s@nmu.one',
            'city': 'Дніпро',
            'birthDate': '01.01.2001',
        },
        {
            'image': static('img/students/vladislav.jfif'),
            'name': 'Владислав',
            'surname': 'Федорець',
            'patronymic': 'Романович',
            'speciality': '121-19-1',
            'faculty': 'ФІТ',
            'email': 'fedorets.v.r@nmu.one',
            'city': 'Дніпро',
            'birthDate': '01.01.2001',
        },
        {
            'image': static('img/students/andriy.jfif'),
            'name': 'Андрій',
            'surname': 'Балян',
            'patronymic': 'Давідович',
            'speciality': '121-19-1',
            'faculty': 'ФІТ',
            'email': 'balian.a.d@nmu.one',
            'city': 'Дніпро',
            'birthDate': '01.01.2001',
        },
        {
            'image': static('img/students/karina.jfif'),
            'name': 'Карина',
            'surname': 'Жовнір',
            'patronymic': 'Олександрівна',
            'speciality': '121-19-1',
            'faculty': 'ФІТ',
            'email': 'zhovnir.k.o@nmu.one',
            'city': 'Дніпро',
            'birthDate': '01.01.2001',
        },
    ]
    university_info = {
        'image': 'https://lh3.googleusercontent.com/p/AF1QipM1veB6FAnZWcPP4jLBLpv1j1wkqJx4kiIpErtd=s1360-w1360-h1020',
        'title': 'Національний ТУ «Дніпровська політехніка»',
        'body': 'Національний технічний університет «Дніпровська політехніка» — провідний вищий навчальний заклад профілю України, заснований 16 червня 1899 р., розташований у місті Дніпро, Україна. Найстаріший вищий гірничий навчальний заклад в Україні, заснований як Катеринославський інститут.',
        'address': 'проспект Дмитра Яворницького, 19, Дніпро',
        'phone': '056 744 1411',
    }
    # return JsonResponse(data, status=200, safe=False)
    # return HttpResponse(data)
    return {'students': data, 'university': university_info}

@login_required(login_url='/login/')
def get_students(request, university):
    if university == 'ntu':
        data = get_ntu_students(request)
        return render(request, 'board/students.html', {'students':data['students'], 'university': data['university']})
    return render(request, 'board/students.html', {'students':[], 'university':[]})

def how_24h_works(request): 
    return render(request, 'others/24_hour.html')
def about_cookies(request): 
    return render(request, 'others/about_cookies.html')
def others_page(request): 
    return render(request, 'board/adaptive_others_page.html')
def privacy_policy(request):
    return render(request, 'others/privacy_policy.html')
def website_rules(request):
    return render(request, 'others/website_rules.html')
def lawbook(request):
    return render(request, 'others/lawbook.html')
def about_us(request):
    return render(request, 'others/about_us.html')
def for_employers(request):
    return render(request, 'others/for_employers.html')

def error_to_admin(request):
    a=1/0
    return render(request, 'others/exception.html')

def handler400_error(request, *args, **argv):
    return render(request, "others/400.html")
def handler403_error(request, *args, **argv):
    return render(request, "others/403.html")
def handler404_error(request, *args, **argv):
    return render(request, "others/404.html")
def handler500_error(request, *args, **argv):
    return render(request, "others/500.html")




            
def tw_blog(request):
    blog_obj = TeenworkBlog.objects.filter(status = 'published')
    paginator = Paginator(blog_obj, 20)

    page = request.GET.get('page')
    try:
        response = paginator.page(page)
    except PageNotAnInteger:
        response = paginator.page(1)
    except EmptyPage:
        response = paginator.page(paginator.num_pages)
    
    time_now1 = str(datetime.today().date().day).zfill(2) + '.' + str(datetime.today().date().month).zfill(2) + '.' + str(datetime.today().date().year).zfill(2)
    time_now2 = str(datetime.today().date().day-1).zfill(2) + '.' + str(datetime.today().date().month).zfill(2) + '.' + str(datetime.today().date().year).zfill(2) # для того, чтобы вместо дня 1 марта превратить в 01 марта

    context={
        'blog_obj':response, 
        'time_now1': time_now1,
        'time_now2': time_now2,
    }

    return render(request, 'others/blog.html', context)

from django.db.models import F
def tw_blog_post(request, slug):
    if TeenworkBlog.objects.filter(slug=slug).exists:
        blog_obj = TeenworkBlog.objects.get(slug=slug)
        TeenworkBlog.objects.filter(slug=slug).update(views=F('views')+1)
        return render(request, 'others/blog_post.html', {'blog_obj':blog_obj})
    else:
        return redirect('account:tw_blog')



'''
pip install googletrans==3.1.0a0
'''

def translate_str(string):
    string_trans = ''

backend/board/templates/board/base.html
{% load static %}  
{% load i18n %} 
{% load remove_lang_code_from_url %}


<!DOCTYPE html>
<html lang="{{request.LANGUAGE_CODE}}">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="alternate" href="https://teenwork.com.ua{{request.path|remove_lang_code_from_url}}" hreflang="uk-UA">
  <link rel="alternate" href="https://teenwork.com.ua/ru{{request.path|remove_lang_code_from_url}}" hreflang="ru-UA">
  <link rel="canonical" href="https://teenwork.com.ua{{request.path}}">
  <meta http-equiv="Content-Language" content="{{request.LANGUAGE_CODE}}">

  <title>{% block title %}{% endblock %}</title>
  {% block head %}{% endblock %}
 
  <meta name="robots" content="index,follow,noodp"><!-- Все поисковые системы -->
  <meta name="googlebot" content="index,follow"><!-- Указание отдельно для Google -->

  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet">
  <link href="{% static 'css/cookies_things.css' %}" type="text/css" rel="stylesheet">
  <link rel="stylesheet" media="(max-width: 1367px)" href="{% static 'css/adaptive_index.css' %}">
  
  <link rel="shortcut icon" href="{% static 'img/icons/teenwork.ico' %}" type="image/x-icon">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

  {% block styles %}{% endblock %}
</head>
<body>
  <div class="main">
    <div class="test">
      <a href="{% url 'board:index' %}"><img src="{% static 'img/logo.svg' %}" alt="{% translate 'Логотип сервиса для работы студентов Teenwork' %}" class="logo" title="{% translate 'Teenwork - работа для студентов и не только' %}"></a>

      {% get_available_languages as LANGUAGES %}
      {% get_language_info_list for LANGUAGES as languages %}
      <div class="langs">
        <a href="/" class="uk">Українська</a> 
        <input type="checkbox" name="lang_checkbox" id="lang_checkbox" value="">
        <a href="/{{languages.0.code}}/" class="en">English</a> 
      </div>
      
      <ul class="test_ul">
        <li>
          <div class="account"><div class="account_icon"> <img src="{% static 'img/profile.svg' %}" alt="">
            {% if user.is_authenticated %}
            {{user.username}}</div>
            <div class="dropdown-content">
              <a href="{% url 'account:profile_edit' %}">{% translate "Открыть профиль" %}</a>
              <a href="{% url 'account:profile' %}">{% translate "Мои объявления" %}</a>
              <a href="{% url 'chat:show_chats' %}">{% translate "Сообщения" %}</a>
              <a href="{% url 'account:logout' %}">{% translate "Выйти" %}</a>
            </div>
            {% else %}
            <a href="{% url 'account:login' %}">{% translate "Войти в профиль" %}</a></div>
            {% endif %}
          </div>
        </li>

        <li>
          <div class="telegram">
            <div>
              <a href="{% url 'telegram_filter:get_unique_code' %}" class="tgrm_icon"> 
                <img src="{% static 'img/telegram.svg' %}" alt="" class="telegram_icon">
                Bot</a></div>
            <div class="prompt_telegram_bot">Телеграм Бот</div>
          </div>
        </li>
        
        <li>
          <div class="add_post"><span class=add_cross>+</span><a href="{% url 'board:add' %}">{% translate "Добавить объявление" %}</a></div>
        </li>

        <li>
          <a href="{% url 'account:favourite_list' %}" >
            <img src="{% static 'img/full_heart.svg' %}" alt="" class="liked_posts">
          </a>
        </li>

        <li><span class="toggle"></span></li>
      </ul>
    </div>

  <div class="accept_cookie">
    <div class="cookie_photo">
        <img src="{% static 'img/cookie.svg'%}" alt="">
    </div>
    <span class="cookie_text">
        {% translate "Мы будем использовать куки, чтобы запоминать Ваши предпочтения, менять тему сайта и многое полезное" %}
    </span>
    <div class="cookie_buttons">
        <div class="cookie_know_more">
            <a href="{% url 'board:about_cookies' %}"><span class="cookie_know_more_text">{% translate "Узнать больше" %}</span></a>
        </div>
        <button type="button" class="cookie_submit_button">{% translate "Принять" %}</button>
    </div>
  </div>


  <div class="try_24h">
    <div class="try_24h_photo">
        <img src="{% static 'img/24h.svg'%}" alt="">
    </div>
    <span class="try_24h_text">
        {% translate "Давайте опубликуем объявление без регистрации? Попробуйте, это бесплатно" %}
    </span>
    <div class="try_24h_buttons">
      <button type="button" class="try_24h_submit_button">{% translate "Окей" %}</button>
        <div class="try_24h_know_more">
          <a href="{% url 'board:how_24h_works' %}" target="_blank"><span class="try_24h_know_more_text">{% translate "Как это работает?" %}</span></a>
        </div>
    </div>
  </div>


  {% block content %}  {% endblock %}



  

  

<div class="bottom_navigation">
  <ul>
      <li class="home_nav"><a href="{% url 'board:index' %}"><img src="{% static 'img/icons/home_icon.svg' %}" alt=""><span>{% translate "Главная" %}</span></a></li>
      <li class="search_nav"><img src="{% static 'img/icons/search_icon.svg' %}" alt=""><span>{% translate "Поиск" %}</span></li>
      <li class="add_nav"><a href="{% url 'board:add' %}"><img src="{% static 'img/icons/add_icon.svg' %}" alt=""><span>{% translate "Добавить" %}</span></a></li>
      <li class="fav_nav"><a href="{% url 'account:favourite_list' %}"><img src="{% static 'img/full_heart.svg' %}" alt=""><span>{% translate "Избранные" %}</span></a></li>
      <li class="others_nav"><a href="{% url 'board:others_page' %}"><img src="{% static 'img/icons/others_icon.svg' %}" alt=""><span>{% translate "Другое" %}</span></a></li>
  </ul>
</div>
<div class="main_dark_search"></div>
<div class="adt_more_dark"></div>

  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <script async src="{% static 'js/main_instantly.js' %}" type="text/javascript"></script>
</div>
<footer>
    <div class="navigation">
      <span>{% translate "Интересные ссылки" %}</span>
      <ul>
        <li><a href="{% url 'board:index' %}">{% translate "Главная" %}</a></li>
        <li><a href="{% url 'board:add' %}">{% translate "Добавить объявление" %}</a></li>
        <li><a href="{% url 'telegram_filter:get_unique_code' %}">Телеграм Бот</a></li>
        <li><a href="{% url 'chat:show_chats' %}">{% translate "Ваши чаты" %}</a></li>
        <li><a href="{% url 'account:profile' %}">{% translate "Ваши объявления" %}</a></li>
        <li><a href="{% url 'account:profile_edit' %}">{% translate "Профиль" %}</a></li>
      </ul>
    </div>
    <div class="other">
      <span>{% translate "Почитать на досуге" %}</span>
      <ul>
        <li><a href="{% url 'board:for_employers' %}">{% translate "Для работодателей" %}</a></li>
        <li><a href="{% url 'board:privacy_policy' %}">{% translate "Политика конфиденциальности" %}</a></li>
        <li><a href="{% url 'board:website_rules' %}">{% translate "Правила сайта" %}</a></li>
        <li><a href="{% url 'board:lawbook' %}">{% translate "Официальное трудоустройство молодёжи" %}</a></li>
        <br>
        <li><a href="{% url 'board:how_24h_works' %}">{% translate 'Как работает "Публикация на 24ч"' %}</a></li>
        <li><a href="{% url 'board:about_cookies' %}">{% translate "Cookies (надкусанное печенье)" %}</a></li>
        <li><a href="{% url 'board:tw_blog' %}">Наш блог</a></li>
      </ul>
    </div>
    <div class="contacts">
      <span>{% translate "Контакты" %}</span>
      <ul>
        <li><a href="tel:+380(67)-421-63-64" style="color:inherit; text-decoration:none;">+380(67)-421-63-64</a></li>
        <li>{% translate "Идеи, замечания пишите сюда:" %}</li>
        <li>help@teenwork.com.ua</li>
        <li>Telegram: teenwork_ua</li>
      </ul>
      <span style="margin-top: 15px;">{% translate "Присоединяйтесь к нам" %}</span>
      <ul>
        <li>Inst: @teenwork_ua</li>
      </ul>
    </div>
    <div class="about">
      <span class="footer_about_span">Про нас</span>
      <span class="footer_about">
        {% translate "Teenwork - платформа, где студенты и не только могут найти работу, которая им по душе." %}
        <br>
        <a href="{% url 'board:about_us' %}" style="color: inherit;">Узнать ещё</a>
        <br>
        <br>
        &#169;2023 Teenwork
      </span>
    </div>
  </footer>
</body>
    
  <script src="{% static 'js/adaptive_index.js' %}" type="text/javascript"></script>
  <script async src="{% static 'js/script.js' %}" type="text/javascript"></script>
  {% block scripts %}{% endblock %}
</html>

backend/board/templates/board/branch_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

backend/board/templates/board/students.html
{% extends 'board/base.html' %} 
{% load static %} 
{% load i18n %} 
{% load get_age_from_date %}



{% block head %}
    <meta name="subject" content="{% translate 'Ответственные студенты' %}">
    <meta name="description" content="{% translate 'Выберите студента, который поможет в работе!' %}">
{% endblock %}

{% block styles %}
<link href="{% static 'css/students.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block title %}{% translate 'Ответственные студенты' %}{% endblock %}

{% block content %} 
    <div class="all_students">   
        <div class="students_block">
            {% for student in students %}
                <div class="student_block">
                    <img class="student_img" src="{{student.image}}" alt="{% translate 'Фото студента' %} {{student.name}} {{student.surname}}">
                    <div class="student_info">
                        <div class="student_name"><strong>{{student.name}} {{student.surname}}</strong></div>
                        <div class="student_age">{{student.birthDate|get_age_from_date}} {% translate 'лет' %}</div>
                        <div class="student_university_info">{{student.speciality}}, {{student.faculty}}, {{student.city}}</div>
                    </div>
                    <a class="write_to_student" href="mailto:{{student.email}}">{% translate 'Написать' %}</a>
                </div>
            {% empty %}
                <h1>{% translate 'К сожалению, пока студентов нет. Вернитесь сюда завтра!' %}</h1>
            {% endfor %}
        </div>
        <div class="university_info">
            <img src="{{university.image}}" alt="{% translate 'Фото университета' %} {{university.title}}">
            <span class="university_title"><strong>{{university.title}}</strong></span>
            <span class="university_body">{{university.body}}</span>
            <span class="university_address"><strong>{% translate 'Адрес' %}:</strong> {{university.address}}</span>
            <span class="university_phone"><strong>{% translate 'Позвонить' %}:</strong> <a href="tel:{{university.phone}}">{{university.phone}}</a>
        </div>
    </div> 
{% endblock %}
{% block scripts %}
{% endblock %}