backend/account/urls.py
from django.urls import path, re_path
from account import views as account_views
from telegram_filter import views
from django.contrib.auth import views as auth_views


app_name='account'

urlpatterns = [
    path('profile/', account_views.profile, name='profile'),
    path('profile_edit/', account_views.profile_edit, name='profile_edit'),
    path('by/<slug:username>/', account_views.account, name='account'),
    path('login/', account_views.user_login ,name='login'),
    path('account/user_logout/', account_views.user_logout, name='logout'),
    path('registration/', account_views.registration, name='registration'),
    path('resend_activation_email/', account_views.resend_activation_email, name='resend_activation_email'),
    path('activate/<uidb64>/<token>', account_views.VerificationView.as_view(), name = 'activate'),
    path('set_new_pswrd/<uidb64>/<token>', account_views.SetNewPswrdView.as_view(), name = 'set_new_pswrd'),
    path('reset_email/', account_views.RequestResetEmailView.as_view(), name = 'reset_email'),
    path('unsubscribe/<uidb64>/<token>', account_views.UnsubscribeView.as_view(), name = 'unsubscribe'),

    path('fav/<str:pk>/', account_views.favourite_add, name='favourite_add'),
    path('profile/favourites/', account_views.favourite_list, name='favourite_list'),
]

backend/board/urls.py
from django.shortcuts import render
from django.urls import include, path, re_path
from board import views, api
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework import routers

app_name='board'

# api
router = routers.DefaultRouter()
router.register(r'posts', api.BoardViewSet)
urlpatterns_api = [
    path('main_page_ads/', api.main_page_ads, name='main_page_ads'),
    path('ua_cities/', api.ua_cities, name='ua_cities'),
]
urlpatterns_api += router.urls


urlpatterns_others = [
    path('llm_chat/', views.llm_chat , name='llm_chat'),
    path('llm_generate_job_desc/', views.llm_generate_job_desc, name='llm_generate_job_desc'),

    path('how_24h_works/', views.how_24h_works, name='how_24h_works'),
    path('about_cookies/', views.about_cookies, name='about_cookies'),
    path('others_page/', views.others_page, name='others_page'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('rules/', views.website_rules, name='website_rules'),
    path('lawbook/', views.lawbook, name='lawbook'),
    path('about_us/', views.about_us, name='about_us'),
    path('for_employers/', views.for_employers, name='for_employers'),
    
    path('error_to_admin/', views.error_to_admin, name='error_to_admin'),

    path('blog/<str:slug>/', views.tw_blog_post, name='tw_blog_post'),
    path('blog/', views.tw_blog, name='tw_blog'),
    path('add_blog_post/', views.add_blog_post, name='add_blog_post'),
]

urlpatterns = [
    path('add/', views.add_save , name='add'), 
    path('add/load_image/', views.add_load_image , name='add_load_image'), 
    path('add/get_user_data/', views.add_get_user_data , name='add_get_user_data'), 
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/archive/', views.archive, name='archive'),
    path('', views.index, name='index'),
    path('ad/<str:slug>/', views.advertisement, name='advertisement'),
    path('load_more/',views.load_more,name='load_more'),
    path('get_ntu_students/', views.get_ntu_students, name='get_ntu_students'),
    path('students/<str:university>/', views.get_students, name='get_students'),
    
    path('api/v1/', include(urlpatterns_api)),

]
urlpatterns.extend(urlpatterns_others)
# urlpatterns.extend(urlpatterns_api)

backend/chat/urls.py
from django.urls import path
from . import views
app_name='chat'

urlpatterns = [
    path('', views.show_chats, name = 'show_chats'),
    path('get_last_msg/', views.get_last_msg, name = 'get_last_msg'),
    path('search_chats/', views.search_chats, name = 'search_chats'),

    path('workers_list/', views.workers_list, name='workers_list'),
    path('workers_list_a/<str:slug>/', views.workers_list_a, name='workers_list_a'),

    path('add_worker/', views.add_worker, name='add_worker'),
    path('<str:room>/', views.room, name='room'),
    path('checkview/', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

backend/telegram_filter/urls.py
from django.urls import path, include
from . import views

app_name='telegram_filter'

urlpatterns = [
    # path('telegram/', views.telegram, name='telegram'),
    path('telegram_bot/', views.get_unique_code, name='get_unique_code'),
]

backend/website/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from account.views import user_logout
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from website import settings
from .sitemaps import * # Sitemap
from django.contrib.sitemaps.views import sitemap, index
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name='website'

urlpatterns = [
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'rubric': RubricSitemap,
    'age': AgeSitemap,
    'blog':BlogSitemap,
}


urlpatterns += i18n_patterns (
    # path('admin/', admin.site.urls),
    
    path('chat/', include('chat.urls')),
    path('',include('account.urls', namespace='account')),
    path('', include('telegram_filter.urls', namespace='telegram_filter')),

    path('', include('board.urls', namespace='board')),

    # path('sitemap.xml', sitemap, {'sitemaps':sitemaps}),
    
    path('sitemap.xml', index, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.index'),
    path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path('ckeditor',include('ckeditor_uploader.urls')),

    prefix_default_language=False # чтобы не было /ru/ в строке
)

if 'rosetta' in settings.INSTALLED_APPS: # это графический редактор переведённого текста
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

admin.site.index_title = "TeenWork"
admin.site.site_header = "TeenWork Admin"
admin.site.site_title = "Admin"


# errors handlers
handler400 = 'board.views.handler400_error' # неверный запрос
handler403 = 'board.views.handler403_error' # запрещён доступ к странице
handler404 = 'board.views.handler404_error' # неверная страница
handler500 = 'board.views.handler500_error' # проблема с сервером

backend/board/models.py
from django.db import models
from random import randint
from PIL import ExifTags, Image as PIL_Image
import os
from pytils.translit import slugify # djangoвская slugify не принимает кирилицу, поэтому пользоваться этой
from io import BytesIO
from django.core.files.base import ContentFile
import datetime
from django.contrib.sitemaps import ping_google
from django.utils.translation import get_language
import uuid
from django.utils.translation import gettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.safestring import mark_safe

class Board(models.Model):
    title = models.CharField(max_length=70, verbose_name='Название')
    slug = models.SlugField(max_length=150, unique = True,verbose_name='Ссылка')
    content = models.TextField(max_length=5500, null=True, blank=True, verbose_name='Описание') 
    price = models.IntegerField(null=True, blank=True, verbose_name='Зарплата')
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано') 

    rubric = models.ForeignKey('Rubric', on_delete=models.PROTECT,verbose_name='Рубрика')  
    city = models.CharField(max_length=100,  verbose_name='Город')
    age = models.ForeignKey('Age',null=True, blank=True, on_delete=models.PROTECT,verbose_name='Возраст', related_name='age') 
    currency = models.ForeignKey('Currency', on_delete=models.PROTECT, null=True, verbose_name='Валюта')
    workers_amount = models.IntegerField(null=True, blank=True, verbose_name='Кол-во работников')

    author = models.ForeignKey('account.Account',null=True, on_delete=models.CASCADE, verbose_name='Автор', blank=True)
    author_name = models.CharField(max_length=50, verbose_name='Имя автора', blank=True)
    phone_number = models.CharField(max_length=13, verbose_name='Номер телефона', blank=True)
    email = models.EmailField(verbose_name='Email', blank=True)

    views = models.PositiveIntegerField(default=0, verbose_name='Просмотры')

    #User
    favourites = models.ManyToManyField('account.Account', related_name="favourite", default=None, blank=True, verbose_name = "Понравившиеся публикации")
    workers = models.ManyToManyField('account.Account', related_name="workers", default=None, blank=True, verbose_name = "Принятые на работу")


    STATUS_CHOICES = (
        ('published', 'Published'),
        ('edited', 'Edited'),
        ('draft', 'Draft'),
        ('archive', 'Archive'),
        ('24hour', '24hour'),
        ('24hour_draft', '24hour_draft'),
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')

    # Изменение нашей модели для админ-панели
    class Meta:
        verbose_name_plural=_('Объявления') # verbose - подробный
        verbose_name= _('Объявление')
        ordering=['-published']
    
    # Чтобы в админ-панели отображалось фото
    def image_tag(self):
        images = Image.objects.filter(board=self)
        photos = f''
        for i in images:
            photos += f'<a href="/{i.url}"><img src="/{i}" width="150px" style="margin: 0 10px" /></a>'
        return mark_safe(photos)

    image_tag.short_description = _('Изображения')
    image_tag.allow_tags = True


    def save(self,  *args, **kwargs):
        if not self.pk:
            if Board.objects.filter(title=self.title).exists():
                # extra = str(randint(1, 10000))
                self.slug = slugify(self.title) + "-" + str(uuid.uuid4())
            else:
                self.slug = slugify(self.title)
            super(Board, self).save(*args, **kwargs)
        else:
            super(Board, self).save(*args, **kwargs)

        try:
            ping_google() # Вы можете захотеть «пинговать» Google, когда ваша карта сайта изменится, чтобы он знал, что нужно переиндексировать ваш сайт
        except Exception:
            pass


    def delete(self, *args, **kwargs):
        deleted_adt = DeletedAds.objects.create(title = self.title, content = self.content, price = self.price, 
            published = self.published, rubric = self.rubric, city = self.city, age = self.age,
            currency = self.currency, workers_amount = self.workers_amount, author = str(self.author), author_name = self.author_name, 
            phone_number = self.phone_number, email = self.email, views = self.views, status = self.status, 
        )
        for wrkr in self.workers.all():
            deleted_adt.workers.add(wrkr)
        deleted_adt.save()
        super(Board, self).delete(*args, **kwargs)

    def get_image_filename(instance, filename):
        title = instance.board.title
        slug = slugify(title)
        return "post_images/%s-%s" % (slug, filename) 


    def get_image(self):
        return Image.objects.filter(board=self, position=0).first().image.url
    
    def get_images(self):
        return Image.objects.filter(board=self)



class Image(models.Model):
    image = models.ImageField(max_length=300)
    board = models.ForeignKey(Board, null=True, blank=True, on_delete=models.CASCADE,verbose_name='Объявление')  
    position = models.PositiveSmallIntegerField(default=1, verbose_name=_("Позиция"))
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if self._state.adding: 
            image_dir = self.get_img_dir()
            filename = str(uuid.uuid4()) + '.jpg'

            image = PIL_Image.open(self.image)
            try:
                if image.mode != "RGB":
                    image = image.convert("RGB")
            except:
                pass

            try:
                for orientation in ExifTags.TAGS.keys():
                    if ExifTags.TAGS[orientation] == 'Orientation':
                        break
                exif = dict(image._getexif().items())

                if exif[orientation] == 3:
                    image = image.rotate(180, expand=True)
                elif exif[orientation] == 6:
                    image = image.rotate(270, expand=True)
                elif exif[orientation] == 8:
                    image = image.rotate(90, expand=True)
            except:
                pass
            
            image_io = BytesIO()
            image.save(image_io, format='JPEG', quality=70)
            self.image.save(f'{image_dir}/{filename}', ContentFile(image_io.getvalue()), save=False)
            
        super(Image, self).save(*args, **kwargs)
            

    def get_img_dir(self):
        now = datetime.datetime.now()

        if os.path.isdir(f'images/{now.year}'):
            if os.path.isdir(f'images/{now.year}/{now.month}'):
                return str(f'{now.year}/{now.month}') # return without images because MEDIA_PATH will take care of it while saving
            else:
                os.mkdir(f'images/{now.year}/{now.month}')
                return self.get_img_dir()
        else:
            os.mkdir(f'images/{now.year}')
            return self.get_img_dir()

    
    class Meta:
        verbose_name_plural=_('Фотографии')
        verbose_name= _('Фотография')
        ordering=['id']

class Rubric(models.Model):
    name = models.CharField(max_length=50,db_index=True, verbose_name='Название')

    class Meta:
        verbose_name_plural='Рубрики' 
        verbose_name= 'Рубрика'
        ordering=['name']
    
    def __str__(self):
        return self.name

    def get_absolute_url(self): # sitemap
        if get_language() == 'en':
            return f'/en/?rubriс={self.pk}'
        else:
            return f'/?rubriс={self.pk}'



class Age(models.Model):
    # from board.models import Age
    # for i in range(17,41):
    #     Age.objects.create()
    name = models.PositiveIntegerField(db_index=True, verbose_name='Возраст')

    class Meta:
        verbose_name_plural='Возраста' # verbose - подробный
        verbose_name= 'Возраст'
        ordering=['name']
    
    def __str__(self):
        return f'{self.name}'

    
    def get_absolute_url(self): # sitemap
        if get_language() == 'en':
            return f'/en/?age={self.pk}'
        else:
            return f'/?age={self.pk}'

class Currency(models.Model):
    currency = models.CharField(max_length=10)
    
    class Meta:
        verbose_name_plural='Валюта' # verbose - подробный
        verbose_name= 'Валюта'
    def __str__(self):
        return self.currency

class DeletedAds(models.Model):
    title = models.CharField(max_length=70, verbose_name='Название')
    content = models.TextField(max_length=5500, null=True, blank=True, verbose_name='Описание') 
    price = models.IntegerField(null=True, blank=True, verbose_name='Зарплата')
    published = models.DateTimeField(db_index=True, verbose_name='Опубликовано', editable=False) 

    rubric = models.ForeignKey('Rubric',null=True, on_delete=models.PROTECT,verbose_name='Рубрика')  
    city = models.CharField( max_length=100, null=True, verbose_name='Город')
    age = models.ForeignKey('Age',null=True, on_delete=models.PROTECT,verbose_name='Возраст от', related_name='age_deleted') 
    currency = models.ForeignKey('Currency', on_delete=models.PROTECT, null=True, verbose_name='Валюта')
    workers_amount = models.IntegerField(null=True, blank=True, verbose_name='Кол-во работников')

    author = models.CharField(max_length=50, null=True, verbose_name='Автор', blank=True)
    author_name = models.CharField(max_length=50, verbose_name='Имя автора', blank=True)
    phone_number = models.CharField(max_length=13, verbose_name='Номер телефона', blank=True)
    email = models.EmailField(verbose_name='Email', blank=True)

    views = models.PositiveIntegerField(default=0, verbose_name='Просмотры')

backend/board/templates/others/24_hour.html
{% extends 'board/base.html' %} 
{% load static %} 
{% load i18n %} 

{% block head %}
  <meta name="subject" content="{% translate 'Объявление на 24 часа' %}">
  <meta name="description" content="{% translate 'Как можно опубликовать пробное объявление без регистрации.' %}">
{% endblock %}

{% block styles %}
<link href="{% static 'css/cookies_things.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block title %} {% translate "Объявление на 24 часа" %} - Teenwork {% endblock %}
{% block content %}  

<div class="try_24_how_works">
    <h3 class="try_24h_greeting">{% translate "Здравствуйте" %}!</h3>
    <span class="try_24h_text2">
      {% translate "Мы поняли, что Вас заинтересовала данная тема касательно публикации объявлений без регистрации" %}. <br>
      {% translate "Это интересная новинка, которую мы решили ввести на сайте, чтобы Вы смогли больше узнать о нас" %}.<br>
      {% translate "Также нам важно, чтобы Вы остались в приятном впечатлении от пребывания здесь" %})<br>
    </span>
    <span class="try_24h_how_it_works">
      <h1 style="font-size: 19px;">{% translate "И всё же, как это работает" %}?</h1>
      <span class="text">
        {% translate "Вы можете подать" %} <span class="increase_text">2</span> {% translate "объявления о Ваших вакансиях без регистрации на сайте, просто нажав эту кнопку" %} <div class="add_post_24"><span class="add_cross_24">+</span><a href="{% url 'board:add' %}">{% translate "Добавить объявление" %}</a></div><br>
        {% translate "Ваши объявления будут на сайте" %} <span class="increase_text">{% translate "24 часа" %}</span>, {% translate "то есть одни сутки, после чего удалятся" %}.<br>
        {% translate "Когда Вы привыкните к сайту, Вам понравится работать с нами, Вы можете перейти к регистрации, чтобы подать больше объявлений" %}.<br>
        {% translate "Мы всегда рады Вам" %}!)<br>
      </span>
    </span>
    <span class="why_register">
      <h3>{% translate "Зачем Вам нужна регистрирация" %}?</h3>
      <span class="text">
        {% translate "Расслабьтесь, мы не будем передавать Ваши данные Пентагону" %} :)<br>
        {% translate "Регистрация нужна исключительно в положительном русле - мы сможем давать Вашим работникам, как и работодателям, связь друг с другом" %}.<br>
        {% translate "Вы сможете договариваться друг с другом о встречах. Если Вы работодатель, сможете вести" %} <span class="increase_text"><a href="{% url 'chat:workers_list' %}">{% translate "учёт" %}</a></span> {% translate "нанятых работников по каждому объявлению(Мои объявления -> Принятые на работу)" %}.<br>
        {% translate "Также важная особенность нашего сервиса - использование" %} <span class="increase_text"><a href="{% url 'telegram_filter:get_unique_code' %}">Телеграм Бота</a></span>. В <a href="{% url 'account:profile_edit' %}?tel" class="increase_text">{% translate "настройках" %}</a> {% translate "Вы сможете задать нужные требования боту, какие объявления хотите получать. После публикации Вам сразу приходит письмо" %} "{% translate "счастья" %}" {% translate "в Ваш Телеграм со" %} "{% translate "свежеиспечённым" %}" {% translate "объявлением" %}.<br>
      </span>
    </span>
    <span class="thanks">
      {% translate "Спасибо, что Вы с нами" %}! <br>
      {% translate "Мы неустанно трудимся, чтобы Вам было комфортно работать как и с нами, так и с новыми людьми" %})<br>
    </span>
</div>
{% endblock %}

backend/board/templates/others/about_cookies.html
{% extends 'board/base.html' %} 
{% load static %} 
{% load i18n %} 

{% block head %}
  <meta name="subject" content="{% translate 'Объявление на 24 часа' %}">
  <meta name="description" content="{% translate 'Как можно опубликовать пробное объявление без регистрации.' %}">
{% endblock %}

{% block styles %}
<link href="{% static 'css/cookies_things.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block title %} Про Cookies {% endblock %}
{% block content %}  

<div class="cookies_how_works">
  <img src="{% static 'img/cookie.svg' %}" alt="">
  <span>
    {% translate "Наш сервис использует Cookies (куки). Это небольшие по размеру файлы с данными, расположенные на устройстве пользователя, которые не представляют угрозу и помогают запоминать Ваши предпочтения, такие как: выбор темы сайта, языка и.т.д. Полный перечень Вы можете увидеть, перейдя в консоль разработчика -> Application -> Cookies -> дальше из выпавшего меню выбираете сервис Teenwork и просматриваете" %}.
  </span>
  <span>{% translate "Информация взята из" %} <a href="{% url 'board:privacy_policy' %}">{% translate "Политики Конфиденциальности" %}</a> {% translate "веб-сервиса" %} Teenwork (п. 3.1.)</span>
</div>
{% endblock %}

backend/board/templates/others/blog.html
{% extends 'board/base.html' %} 
{% load static %} 
{% load i18n %} 



{% block head %}
    <meta name="subject" content="{% translate 'Teenwork блог' %}">
    <meta name="description" content="{% translate 'Это раздел блога Teenwork, который рассказывает о работе и подработке для студентов и молодых людей.' %}">
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/teenwork_blog.css' %}">
{% endblock %}

{% block title %}Teenwork Блог{% endblock %}

{% block content %}  

    <h1 class="blog_h1">{% translate "Teenwork блог - статьи для развития и не только" %}</h1>
    {% if request.user.is_staff %}<h3 style="text-align: center;"><a href="{% url 'board:add_blog_post' %}">{% translate "Добавить статью" %}</a></h3>{% endif %}
    <div class="blog">
        <div class="blog_block">
            {% for val in blog_obj %}
                <a href="{% url 'board:tw_blog_post' val.slug %}" class="article">
                    <span>
                        <span class="a_title">{{val.title}}</span>
                        {% if time_now1 == val.published|date:"d.m.Y" %}
                            <span class="a_publ">{% translate "Сегодня" %}</span>
                            <span class="fresh">{% translate "Свежее" %}</span>
                        {% elif time_now2 == val.published|date:"d.m.Y" %}
                            <span class="a_publ">{% translate "Вчера" %}</span>
                            <span class="fresh">{% translate "Свежее" %}</span>
                        {% else %}
                            <span class="a_publ">{{val.published|date:"d.m.Y"}}</span>
                        {% endif %}
                    </span>
                    <span class="a_content">{{val.post_content}}</span>
                </a>
            {% empty %}
                <p>{% translate "Публикаций пока нет, но мы вскоре напишем что-то интересное" %}</p>
            {% endfor %}
        </div>
    </div>
    {% if blog_obj.paginator.num_pages > 1 %}
        <div class="pagination">  
            <div class="pagination_content">
                {% if blog_obj.has_previous %}
                    <a href="?page={{ blog_obj.previous_page_number }}"><span class="pag_arrow_back"></span></a>
                {% endif %}
                    Страница <span class="this_page">{{blog_obj.number}}</span> из {{blog_obj.paginator.num_pages}}
                {% if blog_obj.has_next %}
                    <a href="?page= {{ blog_obj.next_page_number }}"><span class="pag_arrow_forw"></span></a>
                {% endif %}
            </div>
        </div>
    {% endif %}

{% endblock %}

backend/board/templates/others/board_adt_save_btn.html
{% extends 'admin/change_form.html' %}

{% block submit_buttons_bottom %}
    {{ block.super }}
    <div class="submit-row">
        <input type="submit" value="Опубликовать" name="publish_btn" class="default">
        <input type="submit" value="Опубликовать на 24ч" name="publish_24_btn" class="default">
        <input type="submit" value="Удалить без подтвержд." name="delete_btn" style="background: var(--delete-button-bg); border-radius: 4px; padding: 10px 15px; height: 37px; line-height: 15px; color: var(--button-fg);">
    </div>
    
    <!-- Чтобы, если мы подтвержаем объявление в админ-панели не приходило уведомление, что объъявление изменили (когда идёт сигнал, статут не published, а edited) -->
    <script>
        document.getElementsByName('publish_btn')[0].addEventListener('click', function() {
            const select = document.querySelector('#id_status').getElementsByTagName('option')[0];
            select.selected = true;
        });
    </script>
{% endblock %}

backend/board/templates/others/exception.html
{% extends 'board/base.html' %} 
{% load static %} 
{% load i18n %} 



{% block head %}
    <meta name="subject" content="{% translate 'Teenwork Ошибка' %}">
    <meta name="description" content="{% translate 'Случилась непредвиденная ошибка, стоит попробовать ещё раз.' %}">
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/error_pages.css' %}">
{% endblock %}

{% block title %} Teenwork {% translate "ошибка" %}{% endblock %}

{% block content %}  
    <h1 class="h1_error">Teenwork {% translate "ошибка, попробуйте ещё раз" %}</h1>
    <h3 class="h3_error"></h3>
    <span class="span_error"><a a href="#" onclick="event.preventDefault();history.back();">< {% translate "Вернуться назад" %}</a></span>

    <div class="quote">
        <div class="quote_text">{{quote}}</div>
        <div class="quote_author">{{author}}</div>
    </div>
{% endblock %}

backend/board/templates/others/social_nets_btns.html
{% extends 'admin/change_form.html' %}

{% block submit_buttons_bottom %}
    {{ block.super }}


    <div class="submit-row">
        <input type="submit" value="Отправить email" name="send_email_btn" class="default send_email_btn">
        <input type="submit" value="Отправить пробный email" name="send_test_email_btn" class="default send_test_email_btn">
        <input type="submit" value="Удалить без подтвержд." name="delete_btn" style="background: var(--delete-button-bg); border-radius: 4px; padding: 10px 15px; height: 37px; line-height: 15px; color: var(--button-fg);">
    </div>
    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $('.send_email_btn').click(function() {
            $(this).val('Отправляем...')
        });

        $('.send_test_email_btn').click(function() {
            $(this).val('Отправляем...')
        });
    </script>
{% endblock %}

backend/board/templates/others/teenwork_blog_btns.html
{% extends 'admin/change_form.html' %}

{% block submit_buttons_bottom %}
    {{ block.super }}


    <div class="submit-row">
        <input type="submit" value="Опубликовать" name="publish_btn" class="default publish_btn">
        <input type="submit" value="Отправить пробный email" name="send_test_email_btn" class="default send_test_email_btn">
        <input type="submit" value="Удалить без подтвержд." name="delete_btn" style="background: var(--delete-button-bg); border-radius: 4px; padding: 10px 15px; height: 37px; line-height: 15px; color: var(--button-fg);">
    </div>
    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        if($('#id_img_src').val() === '' || $('#id_img_src').val() === null){
            $('#id_img_src').val('/images/social/');
        }

        document.getElementsByName('publish_btn')[0].addEventListener('click', function(e) {
            const select = document.querySelector('#id_status').getElementsByTagName('option')[0];
            select.selected = true;
        });
    </script>
{% endblock %}