backend/account/urls.py
from django.urls import path, re_path
from account import views as account_views
from telegram_filter import views
from django.contrib.auth import views as auth_views


app_name='account'

urlpatterns = [
    path('profile/', account_views.profile, name='profile'),
    path('profile_edit/', account_views.profile_edit, name='profile_edit'),
    path('by/<slug:username>/', account_views.account, name='account'),
    path('login/', account_views.user_login ,name='login'),
    path('account/user_logout/', account_views.user_logout, name='logout'),
    path('registration/', account_views.registration, name='registration'),
    path('resend_activation_email/', account_views.resend_activation_email, name='resend_activation_email'),
    path('activate/<uidb64>/<token>', account_views.VerificationView.as_view(), name = 'activate'),
    path('set_new_pswrd/<uidb64>/<token>', account_views.SetNewPswrdView.as_view(), name = 'set_new_pswrd'),
    path('reset_email/', account_views.RequestResetEmailView.as_view(), name = 'reset_email'),
    path('unsubscribe/<uidb64>/<token>', account_views.UnsubscribeView.as_view(), name = 'unsubscribe'),

    path('fav/<str:pk>/', account_views.favourite_add, name='favourite_add'),
    path('profile/favourites/', account_views.favourite_list, name='favourite_list'),
]

backend/board/urls.py
from django.shortcuts import render
from django.urls import include, path, re_path
from board import views, api
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework import routers

app_name='board'

# api
router = routers.DefaultRouter()
router.register(r'posts', api.BoardViewSet)
urlpatterns_api = [
    path('main_page_ads/', api.main_page_ads, name='main_page_ads'),
    path('ua_cities/', api.ua_cities, name='ua_cities'),
]
urlpatterns_api += router.urls


urlpatterns_others = [
    path('llm_chat/', views.llm_chat , name='llm_chat'),
    path('llm_generate_job_desc/', views.llm_generate_job_desc, name='llm_generate_job_desc'),

    path('how_24h_works/', views.how_24h_works, name='how_24h_works'),
    path('about_cookies/', views.about_cookies, name='about_cookies'),
    path('others_page/', views.others_page, name='others_page'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('rules/', views.website_rules, name='website_rules'),
    path('lawbook/', views.lawbook, name='lawbook'),
    path('about_us/', views.about_us, name='about_us'),
    path('for_employers/', views.for_employers, name='for_employers'),
    
    path('error_to_admin/', views.error_to_admin, name='error_to_admin'),

    path('blog/<str:slug>/', views.tw_blog_post, name='tw_blog_post'),
    path('blog/', views.tw_blog, name='tw_blog'),
    path('add_blog_post/', views.add_blog_post, name='add_blog_post'),
]

urlpatterns = [
    path('add/', views.add_save , name='add'), 
    path('add/load_image/', views.add_load_image , name='add_load_image'), 
    path('add/get_user_data/', views.add_get_user_data , name='add_get_user_data'), 
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/archive/', views.archive, name='archive'),
    path('', views.index, name='index'),
    path('ad/<str:slug>/', views.advertisement, name='advertisement'),
    path('load_more/',views.load_more,name='load_more'),
    path('get_ntu_students/', views.get_ntu_students, name='get_ntu_students'),
    path('students/<str:university>/', views.get_students, name='get_students'),
    
    path('api/v1/', include(urlpatterns_api)),

]
urlpatterns.extend(urlpatterns_others)
# urlpatterns.extend(urlpatterns_api)

backend/chat/urls.py
from django.urls import path
from . import views
app_name='chat'

urlpatterns = [
    path('', views.show_chats, name = 'show_chats'),
    path('get_last_msg/', views.get_last_msg, name = 'get_last_msg'),
    path('search_chats/', views.search_chats, name = 'search_chats'),

    path('workers_list/', views.workers_list, name='workers_list'),
    path('workers_list_a/<str:slug>/', views.workers_list_a, name='workers_list_a'),

    path('add_worker/', views.add_worker, name='add_worker'),
    path('<str:room>/', views.room, name='room'),
    path('checkview/', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

backend/website/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from account.views import user_logout
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from website import settings
from .sitemaps import * # Sitemap
from django.contrib.sitemaps.views import sitemap, index
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name='website'

urlpatterns = [
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'rubric': RubricSitemap,
    'age': AgeSitemap,
    'blog':BlogSitemap,
}


urlpatterns += i18n_patterns (
    # path('admin/', admin.site.urls),
    
    path('chat/', include('chat.urls')),
    path('',include('account.urls', namespace='account')),
    path('', include('telegram_filter.urls', namespace='telegram_filter')),

    path('', include('board.urls', namespace='board')),

    # path('sitemap.xml', sitemap, {'sitemaps':sitemaps}),
    
    path('sitemap.xml', index, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.index'),
    path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path('ckeditor',include('ckeditor_uploader.urls')),

    prefix_default_language=False # чтобы не было /ru/ в строке
)

if 'rosetta' in settings.INSTALLED_APPS: # это графический редактор переведённого текста
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

admin.site.index_title = "TeenWork"
admin.site.site_header = "TeenWork Admin"
admin.site.site_title = "Admin"


# errors handlers
handler400 = 'board.views.handler400_error' # неверный запрос
handler403 = 'board.views.handler403_error' # запрещён доступ к странице
handler404 = 'board.views.handler404_error' # неверная страница
handler500 = 'board.views.handler500_error' # проблема с сервером

backend/chat/models.py
from django.db import models
from datetime import datetime

class Room(models.Model):
    name = models.CharField(max_length = 500, verbose_name='Чат')
    ad_fk = models.ForeignKey('board.Board', on_delete=models.CASCADE, verbose_name='Объявление №', default=None, null=True)
    participants = models.ManyToManyField('account.Account', related_name="participants", default=None, blank=True, verbose_name = "Участники чата")

class Message(models.Model):
    value = models.CharField(max_length = 10000, verbose_name='Сообщение')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, verbose_name='Чат №')
    date = models.DateTimeField(default = datetime.now, blank = True, verbose_name='Дата отправки')
    sender = models.ForeignKey('account.Account', on_delete=models.SET_NULL, verbose_name='Отправитель', null=True)

    class Meta:
        get_latest_by = 'id' # Это нам нужно для того, чтобы мы могли получить последний опубликованный объект в views.py через .latest()

backend/board/views.py
from django.shortcuts import redirect, render
from .models import Board, TeenworkBlog
from .forms import BoardForm, TeenworkBlogForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .services import *
from django.templatetags.static import static
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.contrib.admin.views import decorators
import functools
from googletrans import Translator
from utils.utils import ask_llm, translate_sentence
from django.forms.models import model_to_dict


def staff_member_required(view_func):  # переопределим декоратор
    def _checklogin(request, *args, **kwargs):
        if request.user.is_active and request.user.is_staff:
            return view_func(request, *args, **kwargs)
        else:
            return redirect('board:index')
    return functools.wraps(view_func)(_checklogin)

decorators.staff_member_required = staff_member_required 



def index(request):
    return show_index(request)
@csrf_exempt
def load_more(request):
    return load_more_index_adts(request)

def advertisement(request,slug):
    return show_advertisement(request,slug)


@csrf_exempt
def llm_chat(request):
    messages_list = json.loads(request.body.decode('utf-8'))

    messages_list_str = "\n\n".join([
        f"{msg['type']}:\n{msg['value']}"
        for msg in messages_list
    ])

    prompt = f'''
You are the manager of the Ukrainian platform for teenagers "Teenwork". 
Your task is to respond to users' requests within the scope of your duties as a manager.
Attached below is a chain of messages between the manager (assistant) and the user. 
Based on this chain, give a relevant answer.
Message chain:
-----------------------------
{messages_list_str}
-----------------------------
    '''.strip()
    prompt_en = translate_sentence(prompt)
    res = ask_llm(prompt_en, 'uk')
    res = res.replace('менеджер:', '').strip()

    return JsonResponse({
        'message': res
    })



@csrf_exempt
def llm_generate_job_desc(request):
    title = json.loads(request.body.decode('utf-8'))['title']
    prompt = f'''
    You are the manager of the Ukrainian platform for work for teenagers. 
    Your task is to generate a job description for the user based on the job title
    Generate a job description with 3000 chars.
    Title: {title}
    '''.strip()
    prompt_en = translate_sentence(prompt)
    res = ask_llm(prompt_en, 'uk')
    res = res.replace('менеджер:', '').strip()

    return JsonResponse({
        'description': res
    })


@csrf_exempt 
def add_save(request):
    if request.method =='POST':
        form = BoardForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            add_advert(request, form)
            if request.user.is_authenticated:
                return redirect('account:profile')
            return redirect('board:index')
        else:
            print(form.errors)
            if request.user.is_authenticated:
                context = {
                    'form':form,
                    'not_registered':False,
                }    
            else:
                context = {
                    'form':form,
                    'not_registered':True,
                }    
            return render(request, 'board/add.html', context)
    else:
        form = BoardForm()
        if request.user.is_authenticated:
            context={
                'form':form,
                'not_registered':False,
            }       
        else:
            context={
                'form':form,
                'not_registered':True,
            }        
        return render(request, 'board/add.html', context) 

def add_get_user_data(request):
    return get_user_data(request)
    

@login_required(login_url='/login/')
def edit(request, pk):
    return edit_adt(request, pk)
 
@login_required(login_url='/login/')
def delete(request,pk):
    if request.user == Board.objects.get(pk=pk).author:
        Board.objects.get(pk=pk).delete()
        return redirect('/profile/')
    else:
        return redirect('/profile/')

@login_required(login_url='/login/')
def archive(request, pk):
    return archive_adt(request, pk)

@login_required(login_url='/login/')
def get_ntu_students(request):
    # also we can search students, who are registered in out service
    # data = Account.objects.filter(im_working_student=True, email__contains="@nmu.one")
    
    data = [
        {
            'image': static('img/students/dmytro.jfif'),
            'name': 'Дмитро',
            'surname': 'Буслов',
            'patronymic': 'Юрійович',
            'speciality': '121-19-1',
            'faculty': 'ФІТ',
            'email': 'buslov.d.y@nmu.one',
            'city': 'Дніпро',
            'birthDate': '01.01.2001',
        },
        {
            'image': static('img/students/kristina.jfif'),
            'name': 'Кристина',
            'surname': 'Андрющенко',
            'patronymic': 'Сергіївна',
            'speciality': '121-19-1',
            'faculty': 'ФІТ',
            'email': 'andriushchenko.k.s@nmu.one',
            'city': 'Дніпро',
            'birthDate': '01.01.2001',
        },
        {
            'image': static('img/students/vladislav.jfif'),
            'name': 'Владислав',
            'surname': 'Федорець',
            'patronymic': 'Романович',
            'speciality': '121-19-1',
            'faculty': 'ФІТ',
            'email': 'fedorets.v.r@nmu.one',
            'city': 'Дніпро',
            'birthDate': '01.01.2001',
        },
        {
            'image': static('img/students/andriy.jfif'),
            'name': 'Андрій',
            'surname': 'Балян',
            'patronymic': 'Давідович',
            'speciality': '121-19-1',
            'faculty': 'ФІТ',
            'email': 'balian.a.d@nmu.one',
            'city': 'Дніпро',
            'birthDate': '01.01.2001',
        },
        {
            'image': static('img/students/karina.jfif'),
            'name': 'Карина',
            'surname': 'Жовнір',
            'patronymic': 'Олександрівна',
            'speciality': '121-19-1',
            'faculty': 'ФІТ',
            'email': 'zhovnir.k.o@nmu.one',
            'city': 'Дніпро',
            'birthDate': '01.01.2001',
        },
    ]
    university_info = {
        'image': 'https://lh3.googleusercontent.com/p/AF1QipM1veB6FAnZWcPP4jLBLpv1j1wkqJx4kiIpErtd=s1360-w1360-h1020',
        'title': 'Національний ТУ «Дніпровська політехніка»',
        'body': 'Національний технічний університет «Дніпровська політехніка» — провідний вищий навчальний заклад профілю України, заснований 16 червня 1899 р., розташований у місті Дніпро, Україна. Найстаріший вищий гірничий навчальний заклад в Україні, заснований як Катеринославський інститут.',
        'address': 'проспект Дмитра Яворницького, 19, Дніпро',
        'phone': '056 744 1411',
    }
    # return JsonResponse(data, status=200, safe=False)
    # return HttpResponse(data)
    return {'students': data, 'university': university_info}

@login_required(login_url='/login/')
def get_students(request, university):
    if university == 'ntu':
        data = get_ntu_students(request)
        return render(request, 'board/students.html', {'students':data['students'], 'university': data['university']})
    return render(request, 'board/students.html', {'students':[], 'university':[]})

def how_24h_works(request): 
    return render(request, 'others/24_hour.html')
def about_cookies(request): 
    return render(request, 'others/about_cookies.html')
def others_page(request): 
    return render(request, 'board/adaptive_others_page.html')
def privacy_policy(request):
    return render(request, 'others/privacy_policy.html')
def website_rules(request):
    return render(request, 'others/website_rules.html')
def lawbook(request):
    return render(request, 'others/lawbook.html')
def about_us(request):
    return render(request, 'others/about_us.html')
def for_employers(request):
    return render(request, 'others/for_employers.html')

def error_to_admin(request):
    a=1/0
    return render(request, 'others/exception.html')

def handler400_error(request, *args, **argv):
    return render(request, "others/400.html")
def handler403_error(request, *args, **argv):
    return render(request, "others/403.html")
def handler404_error(request, *args, **argv):
    return render(request, "others/404.html")
def handler500_error(request, *args, **argv):
    return render(request, "others/500.html")




            
def tw_blog(request):
    blog_obj = TeenworkBlog.objects.filter(status = 'published')
    paginator = Paginator(blog_obj, 20)

    page = request.GET.get('page')
    try:
        response = paginator.page(page)
    except PageNotAnInteger:
        response = paginator.page(1)
    except EmptyPage:
        response = paginator.page(paginator.num_pages)
    
    time_now1 = str(datetime.today().date().day).zfill(2) + '.' + str(datetime.today().date().month).zfill(2) + '.' + str(datetime.today().date().year).zfill(2)
    time_now2 = str(datetime.today().date().day-1).zfill(2) + '.' + str(datetime.today().date().month).zfill(2) + '.' + str(datetime.today().date().year).zfill(2) # для того, чтобы вместо дня 1 марта превратить в 01 марта

    context={
        'blog_obj':response, 
        'time_now1': time_now1,
        'time_now2': time_now2,
    }

    return render(request, 'others/blog.html', context)

from django.db.models import F
def tw_blog_post(request, slug):
    if TeenworkBlog.objects.filter(slug=slug).exists:
        blog_obj = TeenworkBlog.objects.get(slug=slug)
        TeenworkBlog.objects.filter(slug=slug).update(views=F('views')+1)
        return render(request, 'others/blog_post.html', {'blog_obj':blog_obj})
    else:
        return redirect('account:tw_blog')



'''
pip install googletrans==3.1.0a0
'''

def translate_str(string):
    string_trans = ''

backend/board/templates/chat/chats.html
{% extends 'board/base.html' %} 
{% load static %} 
{% load i18n %} 



{% block head %}
    <meta name="subject" content="{% translate 'Чаты' %}">
    <meta name="description" content="{% translate 'Ваши чаты - начните диалог с другими пользователями платформы!' %}">
{% endblock %}


{% block styles %}
<link href="{% static 'css/adaptive_chats.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block title %} {% translate "Чаты" %} - Teenwork {% endblock %}
{% block content %}

    <div class="page_title">
        <a href="#" onclick="history.back();" class="come_back"><em class="arrow-back"></em></a>
        <span>{% translate "Ваши чаты" %}</span>
    </div>
    

    <h1 class="header_chats">
		{% translate "Ваши чаты" %}:
	</h1>
	

	<div class="chats_search_field">
		<span class="chats_search">{% translate "Найти чат" %}</span>
        <input type="text" id="searchInput" name="searchInput">
	</div>

	
	<div class="line"></div>
    <div id="sms_field">
        {% for val in my_rooms %}
            <a href="{% url 'chat:room' val.name %}" id="sms_a">
                <input type="hidden" value="{{val.name}}" class="room_id"">
                <span class="sms_number">
                    {{forloop.counter}}
                </span>
                <div class="sms">
                    <span class="adt_name_chat">
                        {{val.ad_fk.title}}
                    </span>
                    <span class="sender_name_chat">
                        {{val.ad_fk.author.username}}
                    </span>
                    <span class="sms_name_chat">
                        ...
                    </span>
                </div>
            </a>    
        {% endfor %}
    </div>
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
<script src="{% static 'js/chats.js' %}"></script>

{% endblock %}

backend/board/templates/chat/room.html
{% load static %}
{% load i18n %} 
<!DOCTYPE html>
<html lang="{{request.LANGUAGE_CODE}}">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Language" content="{{request.LANGUAGE_CODE}}">
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet">
  <link href="{% static 'css/room.css' %}" type="text/css" rel="stylesheet">
  <link href="{% static 'css/adaptive_room.css' %}" type="text/css" rel="stylesheet">
  <link rel="shortcut icon" href="{% static 'img/icons/teenwork.ico' %}" type="image/x-icon">

  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

  <title>Чат - {{room.ad_fk.title}}</title>
</head>
<body>
<div class="main">
  <div class="container">
    <div class="title">
      <a href="{% url 'account:account' participant.username %}" class="emp_a">
        {% if show_add_workers_icon %}
          <span class="emp_data">
            {% if participant.image %}
              <img src="{{participant.image.url}}" alt="{% translate 'Фото получателя' %}" class="photo">
            {% else %}
              <img src="{% static 'img/user.svg' %}" class="photo" alt="{% translate 'Нет фото получателя' %}">
            {% endif %}
            <span class="emp_name">
              {% if participant.first_name and participant.last_name %}
                {{participant.first_name}} {{participant.last_name}}
              {% elif participant.first_name %}
                {{participant.first_name}}
              {% elif participant.last_name %}
                {{participant.last_name}}
              {% else %}
                {{participant.username}}
              {% endif %}
              </span>

            <form method="POST">
              {% csrf_token %}
              <input type="hidden" name="room_id" id="room_id" value="{{room.id}}"/>
              <div class="add_worker"><img src="{% static 'img/white_tick.svg'%}" alt=""></div>
            </form>
          </span>
        {% else %}
          <span class="emp_data">
            {% if participant.image %}
              <img src="{{participant.image.url}}" alt="{% translate 'Фото получателя' %}" class="photo">
            {% else %}
              <img src="{% static 'img/user.svg' %}" class="photo" alt="{% translate 'Нет фото получателя' %}">
            {% endif %}
            <span class="emp_name">{{participant}}</span>
          </span>
        {% endif %}
      </a>
      
      <span class="add_worker_help_text">
        {% translate "Вы приняли нового сотрудника. Поздравляем! Осталось" %} <strong>{{workers_amount}}</strong> {% translate "вакансии" %}. 
        {% translate "Всех людей можно посмотреть" %} <a href="{% url 'chat:workers_list'%}">{% translate "здесь" %}</a>
      </span>


      
      <a href="{% url 'board:advertisement' slug=room.ad_fk.slug%}" title="Перейти к объявлению" class="adt_title_a">
        <div class="adt_title">
          <img src="{{room.ad_fk.get_image}}" alt="" >
          <span class="title_name">{{room.ad_fk.title}}</span>
          <span class="sal">{{room.ad_fk.price}} {{room.ad_fk.currency}}</span>
        </div>
      </a>
    </div>

  
    <div class="main_chat">
      <div id="messages_field">
        <div class="loading" role="status">{% translate "Загрузка" %}...</div>
      </div>
    </div>

    <form method="POST" id="post-form">
      {% csrf_token %}
      <textarea id="message" placeholder='{% translate "Сообщение" %}' name="message"></textarea>
      <input type="hidden" name="sender" id="sender" value="{{this_user}}"/>
      <input type="hidden" name="receiver" id="receiver" value="{{participant}}"/>
      <input type="hidden" name="room_name" id="room_name" value="{{room.name}}"/>
      <button type="submit" id="send_msg_room">
        <img src="{% static 'img/send_msg.svg' %}" alt="">
      </button>
    </form>
  </div>
</div>
</body>

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<script src="{% static 'js/chats.js' %}" type="text/javascript"></script>
<script src="{% static 'js/main_instantly.js' %}" type="text/javascript"></script>
<script async src="{% static 'js/script.js' %}" type="text/javascript"></script>

<script>
  document.getElementById('message').value = '{{msg}}';
</script>

</html>

backend/board/templates/chat/workers_list.html
{% extends 'board/base.html' %} 
{% load static %} 
{% load i18n %} 

{% block head %}
  <meta name="subject" content="{% translate 'Список работников, которых Вы добавили' %}">
  <meta name="description" content="{% translate 'Когда Вы добавляете публикацию, можно нанять работника, нажав галочку в переписке с ним.' %}">
{% endblock %}


{% block styles %}
<link href="{% static 'css/workers_list.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block title %} {% translate "Работники" %} на Teenwork {% endblock %}
{% block content %}
<h1 class="workers_greeting">{% translate "Ваши работники, которых Вы добавили, нажав" %} <div class="add_worker"><img src="{% static 'img/white_tick.svg'%}" alt=""></div> {% translate "в чате" %}</h1>
<div class="line"></div>

{% for val in board_obj %}
{% if val.workers.all %}
<div class="workers_field">
  <a href="{% url 'board:advertisement' slug=val.slug%}" title="Перейти к объявлению" class="adt_a">
    <div class="adt_name">
      <img src="{{val.get_image}}" alt="{% translate 'Фото Вашего объявления' %} - {{val.title}}">
      <span class="adt_title">{{val.title}}</span>
    </div>
  </a>
  
  <ul>
    {% for worker in val.workers.all %}
    <form method="POST" action="{% url 'chat:workers_list' %}">
        <li class="worker_li">
            {% csrf_token %}
            {% if worker.image %}
            <img src="{{worker.image.url}}" alt="{% translate 'Фото работника' %} {{worker.username}}" class="photo">
            {% else %}
            <img src="{% static 'img/user.svg' %}" class="photo" alt="{% translate 'У работника' %} {{worker.username}} {% translate 'нет фото профиля' %}">
            {% endif %}
            <a href="{% url 'chat:workers_list_a' slug=val.slug %}" aria-multiline="" title="{% translate 'Перейти в чат' %}">{{worker.username}}</a>
            <input type="hidden" name="worker" value="{{worker.email}}">
            <input type="hidden" name="slug" value="{{val.slug}}">
            <input type="submit" value="{% translate 'Удалить' %} " class="remove_worker">
        </li>
    </form>
    {% endfor %}
  </ul>
</div>
{% endif %}
{% endfor %}

{% endblock %}