backend/account/urls.py
from django.urls import path, re_path
from account import views as account_views
from telegram_filter import views
from django.contrib.auth import views as auth_views


app_name='account'

urlpatterns = [
    path('profile/', account_views.profile, name='profile'),
    path('profile_edit/', account_views.profile_edit, name='profile_edit'),
    path('by/<slug:username>/', account_views.account, name='account'),
    path('login/', account_views.user_login ,name='login'),
    path('account/user_logout/', account_views.user_logout, name='logout'),
    path('registration/', account_views.registration, name='registration'),
    path('resend_activation_email/', account_views.resend_activation_email, name='resend_activation_email'),
    path('activate/<uidb64>/<token>', account_views.VerificationView.as_view(), name = 'activate'),
    path('set_new_pswrd/<uidb64>/<token>', account_views.SetNewPswrdView.as_view(), name = 'set_new_pswrd'),
    path('reset_email/', account_views.RequestResetEmailView.as_view(), name = 'reset_email'),
    path('unsubscribe/<uidb64>/<token>', account_views.UnsubscribeView.as_view(), name = 'unsubscribe'),

    path('fav/<str:pk>/', account_views.favourite_add, name='favourite_add'),
    path('profile/favourites/', account_views.favourite_list, name='favourite_list'),
]

backend/board/urls.py
from django.shortcuts import render
from django.urls import include, path, re_path
from board import views, api
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework import routers

app_name='board'

# api
router = routers.DefaultRouter()
router.register(r'posts', api.BoardViewSet)
urlpatterns_api = [
    path('main_page_ads/', api.main_page_ads, name='main_page_ads'),
    path('ua_cities/', api.ua_cities, name='ua_cities'),
]
urlpatterns_api += router.urls


urlpatterns_others = [
    path('llm_chat/', views.llm_chat , name='llm_chat'),
    path('llm_generate_job_desc/', views.llm_generate_job_desc, name='llm_generate_job_desc'),

    path('how_24h_works/', views.how_24h_works, name='how_24h_works'),
    path('about_cookies/', views.about_cookies, name='about_cookies'),
    path('others_page/', views.others_page, name='others_page'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('rules/', views.website_rules, name='website_rules'),
    path('lawbook/', views.lawbook, name='lawbook'),
    path('about_us/', views.about_us, name='about_us'),
    path('for_employers/', views.for_employers, name='for_employers'),
    
    path('error_to_admin/', views.error_to_admin, name='error_to_admin'),

    path('blog/<str:slug>/', views.tw_blog_post, name='tw_blog_post'),
    path('blog/', views.tw_blog, name='tw_blog'),
    path('add_blog_post/', views.add_blog_post, name='add_blog_post'),
]

urlpatterns = [
    path('add/', views.add_save , name='add'), 
    path('add/load_image/', views.add_load_image , name='add_load_image'), 
    path('add/get_user_data/', views.add_get_user_data , name='add_get_user_data'), 
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/archive/', views.archive, name='archive'),
    path('', views.index, name='index'),
    path('ad/<str:slug>/', views.advertisement, name='advertisement'),
    path('load_more/',views.load_more,name='load_more'),
    path('get_ntu_students/', views.get_ntu_students, name='get_ntu_students'),
    path('students/<str:university>/', views.get_students, name='get_students'),
    
    path('api/v1/', include(urlpatterns_api)),

]
urlpatterns.extend(urlpatterns_others)
# urlpatterns.extend(urlpatterns_api)

backend/chat/urls.py
from django.urls import path
from . import views
app_name='chat'

urlpatterns = [
    path('', views.show_chats, name = 'show_chats'),
    path('get_last_msg/', views.get_last_msg, name = 'get_last_msg'),
    path('search_chats/', views.search_chats, name = 'search_chats'),

    path('workers_list/', views.workers_list, name='workers_list'),
    path('workers_list_a/<str:slug>/', views.workers_list_a, name='workers_list_a'),

    path('add_worker/', views.add_worker, name='add_worker'),
    path('<str:room>/', views.room, name='room'),
    path('checkview/', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

backend/telegram_filter/urls.py
from django.urls import path, include
from . import views

app_name='telegram_filter'

urlpatterns = [
    # path('telegram/', views.telegram, name='telegram'),
    path('telegram_bot/', views.get_unique_code, name='get_unique_code'),
]

backend/website/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from account.views import user_logout
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from website import settings
from .sitemaps import * # Sitemap
from django.contrib.sitemaps.views import sitemap, index
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name='website'

urlpatterns = [
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'rubric': RubricSitemap,
    'age': AgeSitemap,
    'blog':BlogSitemap,
}


urlpatterns += i18n_patterns (
    # path('admin/', admin.site.urls),
    
    path('chat/', include('chat.urls')),
    path('',include('account.urls', namespace='account')),
    path('', include('telegram_filter.urls', namespace='telegram_filter')),

    path('', include('board.urls', namespace='board')),

    # path('sitemap.xml', sitemap, {'sitemaps':sitemaps}),
    
    path('sitemap.xml', index, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.index'),
    path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path('ckeditor',include('ckeditor_uploader.urls')),

    prefix_default_language=False # чтобы не было /ru/ в строке
)

if 'rosetta' in settings.INSTALLED_APPS: # это графический редактор переведённого текста
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

admin.site.index_title = "TeenWork"
admin.site.site_header = "TeenWork Admin"
admin.site.site_title = "Admin"


# errors handlers
handler400 = 'board.views.handler400_error' # неверный запрос
handler403 = 'board.views.handler403_error' # запрещён доступ к странице
handler404 = 'board.views.handler404_error' # неверная страница
handler500 = 'board.views.handler500_error' # проблема с сервером

backend/account/forms.py
from django.forms import ModelForm
from account.models import Account
from django import forms

class ProfileEditForm(ModelForm):
    class Meta:
        model = Account
        fields=('image', 'first_name', 'last_name', 'person_age', 'phone_number', 'im_working_student')    

backend/account/views.py
from django.shortcuts import render
from board.models import Board
from account.models import Account
from board.models import TeenworkBlog
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.sites.shortcuts import get_current_site
from .utils import token_generator
from django.conf import settings
from django.db.models import Q

from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes, force_str, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
import datetime
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMultiAlternatives
import re
from .forms import ProfileEditForm
from telegram_filter.models import Telegram
from telegram_filter.forms import TelegramForm
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import get_template


import threading
# view для того, чтобы быстрее отправлять email
class EmailThreading(threading.Thread):
    def __init__(self, email_message):
        self.email_message = email_message
        threading.Thread.__init__(self)

    def run(self):
        self.email_message.send()



@login_required(login_url='/login/')
def profile(request):
    board_obj = Board.objects.filter(author=request.user) 
    time_now1 = str(datetime.today().date().day).zfill(2) + '.' + str(datetime.today().date().month).zfill(2) + '.' + str(datetime.today().date().year).zfill(2)
    time_now2 = str(datetime.today().date().day-1).zfill(2) + '.' + str(datetime.today().date().month).zfill(2) + '.' + str(datetime.today().date().year).zfill(2) # для того, чтобы вместо дня 1 марта превратить в 01 марта

    context={
        'board_obj':board_obj,
        'time_now1':time_now1,
        'time_now2':time_now2,
    }

    return render(request, 'user/profile.html', context)

def account(request, username):
    if Account.objects.filter(username=username).exists():
        board_obj = Board.objects.filter(Q(author=Account.objects.get(username=username).pk), Q(status='published')|Q(status='24hour'))
        user = Account.objects.get(username=username)
        time_now1 = str(datetime.today().date().day).zfill(2) + '.' + str(datetime.today().date().month).zfill(2) + '.' + str(datetime.today().date().year).zfill(2)
        time_now2 = str(datetime.today().date().day-1).zfill(2) + '.' + str(datetime.today().date().month).zfill(2) + '.' + str(datetime.today().date().year).zfill(2) # для того, чтобы вместо дня 1 марта превратить в 01 марта

        context={
            'board_obj':board_obj,
            'requested_user':user,
            'time_now1':time_now1,
            'time_now2':time_now2,
        }

        if user == request.user:
            return redirect('/profile/')


        return render(request, 'user/account.html', context)
    else:
        return HttpResponse('Такий Юзер зник о_о')


@login_required(login_url='/login/')
@csrf_exempt 
def profile_edit(request):
    username = request.user.username
    account = Account.objects.get(username=username)
    tlg_obj = Telegram.objects.get(person=request.user)
    tlg_form = TelegramForm(instance=tlg_obj)
    form = ProfileEditForm(instance=account)
    if request.method == 'POST' and 'profile_edit_btn' in request.POST:
        form = ProfileEditForm(request.POST, instance=account)
        if form.is_valid():
            post = form.save(commit=False)
            if request.FILES.get('img'):
                post.image = request.FILES.get('img')
            post.save()
        return redirect('account:profile_edit')

    if request.method =='POST' and 'tlg_btn' in request.POST:
        tlg_form = TelegramForm(request.POST, instance=tlg_obj)
        if tlg_form.is_valid():
            tel = tlg_form.save(commit=False)
            tel.person = request.user
            tlg_form.save()
            return redirect('account:profile_edit')
        else:  
            return redirect('account:profile_edit')
            
    if request.method == 'POST' and 'delete_account_btn' in request.POST:
        for board_obj in Board.objects.filter(author=request.user):
            board_obj.delete() # чтобы в Deleted Ads сохранить его опублик.объявл.
        Account.objects.get(id=request.user.id).delete()
        return redirect('board:index')

    elif request.method == 'POST':
        data = request.POST.get('data', None)
        isTelegram = request.POST.get('isTelegram', None)

        tel = Telegram.objects.get(person=request.user)
        if data:
            if data == 'checked':
                tel.telegram = True
                data = 'true'
            else:
                tel.telegram = False
                data = 'false'
            tel.save()
            return JsonResponse(data, safe=False)
        elif isTelegram:
            if tel.telegram == True:
                isTelegram = 'true'
            else:
                isTelegram = 'false'
            return JsonResponse(isTelegram, safe=False)

    return render(request, 'user/profile_edit.html', {'form':form, 'account':account, 'tlg_form':tlg_form,})




def registration(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        phone_number = request.POST.get('phone_number')

        if request.method == 'POST':
            data=''
            username_check = request.POST.get('username', None)
            email_check = request.POST.get('email', None)
            phone_number_check = request.POST.get('phone_num', None)

            if username_check:
                if Account.objects.filter(username=username_check.lower()).exists():
                    data='username_taken'
                else:
                    data='username_free'
            elif email_check:
                if Account.objects.filter(email=email_check.lower()).exists():
                    data='email_taken'
                else:
                    data='emil_free'
            elif phone_number_check:
                if Account.objects.filter(phone_number=phone_number_check).exists():
                    data='phone_taken'
                else:
                    data='phone_free'


            return JsonResponse(data, safe=False)
        
        if Account.objects.filter(username=username.lower()).exists() or Account.objects.filter(email=email.lower()).exists() or Account.objects.filter(phone_number=phone_number).exists():
            return redirect('account:registration')
            
        if re.match("^[a-z0-9_]+$", username.lower()) == None:
            return redirect('account:registration')

        user = Account.objects.create_user(username=username.lower(), password=password, email=email.lower(), phone_number=phone_number)
        user.is_active = False # Меняем на True после регистрации
        user.save()

        tlg_user = Telegram.objects.create(person=user)
        tlg_user.save()

        uidb64 = urlsafe_base64_encode(force_bytes(user.pk))

        domain = get_current_site(request).domain
        link = reverse('account:activate', kwargs={'uidb64':uidb64,'token':token_generator.make_token(user)})

        activate_url='https://' + domain + link

        # email_context = {
        #     'user':user,
        #     'activate_url': activate_url,
        # }

        # email_subject = 'Активация профиля'
        # # email_body = 'Здравствуй, ' + user.username + '! Используйте эту ссылку, чтобы подтвердить Ваш аккаунт\n' + activate_url # email_body = render_to_string('registration/email.html')
        # email_body = render_to_string('registration/email.html', email_context)
        # email_msg = EmailMessage(
        #     email_subject,
        #     email_body,
        #     settings.EMAIL_HOST_USER,
        #     [email],
        # )

        # # email_msg.send(fail_silently=False) 

        # EmailThreading(email_msg).start()








        mail_title = "Активація"
        variables = {
            'activate_url': activate_url,
            'watch_here': 'https://' + domain + '/rules/',
        }
        html = get_template('registration/email.html').render(variables)
        text = f'https://teenwork.com.ua/static/img/icons/teenwork.png - ( наше лого :) )\nДавайте підтвердимо Ваш аккаунт\nЩоб почати користуватися Teenwork, просто натисніть кнопку підтвердження адреси електронної пошти нижче:\nПідтвердити\n{activate_url}\nУ вас є питання? Подивіться тут.\nhttps://teenwork.com.ua/rules/\nTeenwork - платформа, де підлітки і не тільки можуть знайти роботу, яка їм до вподоби.'
        
        msg = EmailMultiAlternatives(
            mail_title,
            text,
            settings.EMAIL_HOST_USER,
            [email])
        msg.attach_alternative(html, "text/html")
        # msg.send(fail_silently=False) 
        EmailThreading(msg).start()
        

        return render(request, 'registration/registration_success.html')
    else:
        return render(request, 'registration/registration.html')

def resend_activation_email(request):
    if request.method == 'POST':
        email = request.POST.get('email')

        user = Account.objects.get(email=email)

        uidb64 =urlsafe_base64_encode(force_bytes(user.pk))

        domain = get_current_site(request).domain
        link = reverse('account:activate', kwargs={'uidb64':uidb64,'token':token_generator.make_token(user)})

        activate_url='https://' + domain + link


        mail_title = "Активація"
        variables = {
            'activate_url': activate_url,

backend/board/templates/user/account.html
{% extends 'board/base.html' %}
{% load static %}
{% load i18n %} 




{% block head %}
    <meta name="subject" content="{% translate 'Профиль' %} {{requested_user.username}} на Teenwork">
    <meta name="description" content="{% translate 'Это профиль нашего пользователя' %} {{requested_user.username}}">
{% endblock %}

{% block title %} {% translate "Профиль" %} {{requested_user.username}} на Teenwork{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/profile_account.css' %}">
<link rel="stylesheet" href="{% static 'css/adaptive_profile_account.css' %}">
{% endblock %}

{% block content %}
<h1 class="greeting" style="font-weight: normal; font-size: 24px;">{% translate "Вы сейчас на профиле" %} 
    {% if requested_user.first_name and requested_user.last_name %}
        {{requested_user.first_name}} {{requested_user.last_name}}
    {% elif requested_user.first_name %}
        {{requested_user.first_name}}
    {% elif requested_user.last_name %}
        {{requested_user.last_name}}
    {% else %}
        {{requested_user.username}}
    {% endif %}
    {% if requested_user.is_official %}
        <div class="tick">
            <div class="tick_right"></div>
            <div class="tick_left"></div>
        </div>
        <span class="tick_text">{% translate "Это официальный аккаунт" %}</span>
    {% endif %}
</h1>

<div class="line"></div>

<span id="adt_header" style="display:block;">{% translate "Объявления" %}:</span>

<div class="adt_container"> 
{% for val in board_obj %}
<div class="adt">
    <div class="container">
        <div class="adt_image_block">
            <a href="{% url 'board:advertisement' val.slug %}"  class="adt_a">
                <img class="adt_image zoom" src="{{val.get_image}}" alt="{{val.rubric}}:{{val.title}}">	
            </a>
        </div>
        <div class="container_info">
            <span class="adt_name"> <span class="adt_n">
                <a href="{% url 'board:advertisement' val.slug %}"  class="adt_a">
                    {{val.title}}
                </a>
                </span> 
                {% if val.author.is_official %}
                    <div class="tick">
                        <div class="tick_right"></div>
                        <div class="tick_left"></div>
                    </div>
                    <span class="tick_text">{% translate "Это официальный аккаунт" %}</span>
                {% endif %}
                <span class="adt_salary">{{ val.price }} {{ val.currency }}</span>
            </span> 
            {% if val.age %}
                <span class="adt_age">{% translate "Возраст" %}: {{ val.age }} лет.</span>
            {% else %}
                <span class="adt_age">{% translate "Возраст" %}: {% translate "Все" %}</span>
            {% endif %}
            <span class="adt_rubric">{{val.rubric}}</span>
            <span class="adt_city">{{ val.city }}</span>
            <span class="adt_created">
                {% if time_now1 == val.published|date:"d.m.Y" %}
                    {% translate "Сегодня" %} в {{val.published|date:"H:i"}}
                {% elif time_now2 == val.published|date:"d.m.Y" %}
                    {% translate "Вчера" %} в {{val.published|date:"H:i"}}
                {% else %}
                    {{val.published|date:"d M"}} в {{val.published|date:"H:i"}}
                {% endif %}
                <a href="{% url 'account:favourite_add' val.id%}" class="heart">
                    {% if user in val.favourites.all %}
                    <img src="{% static 'img/full_heart.svg'%}" alt="">
                    {% else %}
                    <img src="{% static 'img/heart.svg'%}" alt="">
                    {% endif %}
                </a> 
            </span>
        </div>
    </div>
</div>
{% empty %}
    <h3 class="empty_list">{% translate "Пока что объявлений нет, давайте" %} <a href="{% url 'board:index' %}?open_search">{% translate "поищем" %} <i class="arrow-forward"></i></a></h3>
{% endfor %}
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function() {
        document.querySelector('.greeting').style.fontSize = '22px';
        document.querySelector('.greeting').style.margin = '0';
        document.querySelector('.greeting').style.textAlign = 'center';
        document.querySelector('.greeting').style.padding = '25px 0px 10px 0';

        document.querySelector('.line').style.height = '0.8px';
        document.querySelector('.line').style.width = '1500px';
        document.querySelector('.line').style.margin = 'auto';
        document.querySelector('.line').style.marginTop = '10px';
        document.querySelector('.line').style.opacity = '0.5';
        document.querySelector('.line').style.background = '#000';

        document.querySelector('.adt_container').style.textAlign = 'initial';
    });
</script>
{% endblock %}

backend/board/templates/user/profile.html
{% extends 'board/base.html' %}
{% load static %}
{% load i18n %} 




{% block head %}
    <meta name="subject" content="{% translate 'Мой профиль на Teenwork' %}">
    <meta name="description" content="{% translate 'Вы можете изменить публикации - удалить, архивировать или поменять содержимое.' %}">
{% endblock %}

{% block title %} {% translate "Профиль" %} на Teenwork {% endblock %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/profile_account.css' %}">
<link rel="stylesheet" href="{% static 'css/adaptive_profile_account.css' %}">
{% endblock %}
{% block content %}

<h1 class="greeting">
    {% translate "Здравствуйте" %}, {% if user.first_name and user.last_name %}
        {{user.first_name}} {{user.last_name}}
    {% elif user.first_name %}
        {{user.first_name}}
    {% elif user.last_name %}
        {{user.last_name}}
    {% else %}
        {{user.username}}
    {% endif %}
    )
    {% if user.is_official %}
        <div class="tick">
            <div class="tick_right"></div>
            <div class="tick_left"></div>
        </div>
        <span class="tick_text">{% translate "Это официальный аккаунт" %}</span>
    {% endif %}
</h1>
<div class="list">
    <ul>
        <li><a href="{% url 'chat:show_chats' %}" class="list_a"><img src="{% static 'img/messages.svg' %}" alt="" class="sms">{% translate "Сообщения" %}</a></li>
        <li><a href="{% url 'account:profile_edit' %}" class="list_a"><img src="{% static 'img/profile_others.svg' %}" alt="" class="sett">{% translate "Настройки" %}</a></li>
        <li><a href="{% url 'account:profile_edit' %}?tel" class="list_a" id="telegram_a"><img src="{% static 'img/telegram_others.svg' %}" alt="" class="tel">Телеграм Бот</a></li>
        <li><a href="{% url 'chat:workers_list' %}" class="list_a"><img src="{% static 'img/hired.svg' %}" alt="" class="workers">{% translate "Принятые на работу" %}</a></li>

    </ul>
</div>

<div class="line"></div>

<span id="adt_header">{% translate "Ваши объявления" %}:</span>

{% for val in board_obj %} 
    {% if val.status == 'archive' %}
    <div class="adt archive">
    {% elif val.status == 'edited'  or val.status == 'draft' %}
    <div class="adt edited">
    {% else %}
    <div class="adt">
    {% endif %}
        <div class="container">
            <div class="adt_image_block">
                <a href="{% url 'board:advertisement' val.slug %}"  class="adt_a">
                    <img class="adt_image zoom" src="{{val.get_image}}" alt="{{val.rubric}}:{{val.title}}">	
                </a>
            </div>
            <div class="container_info">
                <span class="adt_name"> <span class="adt_n">
                    <a href="{% url 'board:advertisement' val.slug %}"  class="adt_a">
                        {{val.title}}
                    </a>
                    </span> 
                    {% if val.author.is_official %}
                        <div class="tick">
                            <div class="tick_right"></div>
                            <div class="tick_left"></div>
                        </div>
                        <span class="tick_text">{% translate "Это официальный аккаунт" %}</span>
                    {% endif %}
                    <span class="adt_salary">{{ val.price }} {{ val.currency }}</span>
                </span> 
                {% if val.age %}
                    <span class="adt_age">{% translate "Возраст" %}: {{ val.age }} лет.</span>
                {% else %}
                    <span class="adt_age">{% translate "Возраст" %}: {% translate "Все" %}</span>
                {% endif %}
                <span class="adt_rubric">{{val.rubric}}</span>
                <span class="adt_city">{{ val.city }}</span>
                <span class="adt_created">
                    {% if time_now1 == val.published|date:"d.m.Y" %}
                        {% translate "Сегодня" %} в {{val.published|date:"H:i"}}
                    {% elif time_now2 == val.published|date:"d.m.Y" %}
                        {% translate "Вчера" %} в {{val.published|date:"H:i"}}
                    {% else %}
                        {{val.published|date:"d M"}} в {{val.published|date:"H:i"}}
                    {% endif %}
                </span>
                <div class="buttons">
                    <span class="edit_btn"><a href="{% url 'board:edit' pk=val.pk %}">{% translate "Изменить" %}</a></span>
                    <span class="archive_btn"><a href="{% url 'board:archive' pk=val.pk %}">{% translate "В архив" %}</a></span>
                    <span class="delete_btn">
                        {% translate "Удалить" %}
                        <div class="pop_delete_adt">
                            <div class="delete_adt_content">
                                <div class="close_pop_delete_adt">+</div>
                                <form method = "POST" action="{% url 'board:delete' pk=val.pk %}">
                                    <h2 class="h2_delete_adt">{% translate "Удалить" %} <div>"{{val.title}}"?</div></h2>
                                    {% csrf_token %}
                                    <input type="submit" value='{% translate "Удалить" %}'  class="delete_adt_btn" style="background: #ff0000;">
                                </form>
                            </div>
                        </div>
                    </span>
                </div>
            </div>
        </div>

    </div>

{% empty %}
    <h3 class="empty_list" style="text-align: center; margin-left: 0;">{% translate "Пока что у Вас объявлений нету, поэтому давайте предложим" %} <a href="{% url 'board:add' %}">
        {% translate "Добавить объявление" %} <i class="arrow-forward"></i></a></h3>
    <div style="width:300px; text-align: center; margin: auto;">
        <img src="{% static 'img/my_ads_empty.svg' %}" alt="Нажмите на сердечко вверху объявления, чтобы добавить в 'Избранные'" style="max-width: 60%;">
    </div>
{% endfor %}
<div style="position: relative; width: 100%; height: 50px;"></div>
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="{% static 'js/profile_edit.js' %}" type="text/javascript"></script>
{% endblock %}